# Create ECR (Optional once public)
# Need to build and push the image

# Create Lambda (15 min timeout)

# Add Lambda permissions

# Allow invoking from Step Functions
Parameters:
  ECRPublicRepoLocation:
    Description: "Location of the image to deploy"
    Type: "String"
    MinLength: 1 # pseudo required
    # MaxLength: 255,
    # AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$",
    Default: "s1k9c2t7/mast-lambda:latest"
Resources:
  # MyECRPullThroughCacheRule:
  #   Type: 'AWS::ECR::PullThroughCacheRule'
  #   Properties:
  #     EcrRepositoryPrefix: 'ecr-public'
  #     UpstreamRegistryUrl: 'public.ecr.aws'
  mastRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: "String"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
        # - !Ref defaultMastRolePolicy
      RoleName: "default-mast-role"
      Tags:
        - Key: "used_by"
          Value: "mast"
    # DependsOn: "defaultTaskExecutionRolePolicy"
  mastLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        "ImageUri": !Sub
          - '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ecr-public/${ECRPublicRepoLocation}' # !Ref ImageUri
          - ECRPublicRepoLocation: !Ref ECRPublicRepoLocation
      PackageType: "Image"
      FunctionName: mast-lambda
      Role: !GetAtt mastRole.Arn
      Tags:
        - Key: "used_by"
          Value: "mast"
      Timeout: 900
    DependsOn: ["mastRole"]
